# Generated by Django 3.2.7 on 2021-09-27 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('matricula', models.CharField(max_length=7, verbose_name='Matricula')),
                ('asientos', models.IntegerField(verbose_name='Asientos')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('id_usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
