# Generated by Django 3.2.7 on 2021-10-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
