# Generated by Django 3.2.7 on 2021-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.FileField(blank=True, default=None, null=True, upload_to='img/'),
        ),
    ]
