# Generated by Django 3.2.7 on 2021-09-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Pasajero')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje', verbose_name='Viaje')),
            ],
        ),
    ]
